# Jekyll
#
# This config file is meant for settings that affect the whole blog, values
# which are expected to be set up once and rarely be edited after that. If
# this file is editedery often, consider using Jekyll's data files
# feature for the data that needs to be updates frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize the site. Look in the HTML files,
# they are accessed via {{ site.title }}, {{ site.email }}, and so on.
# Create any custom variable and it will be accessible
# in the templates via {{ site.myvariable }}.
title: HolaHuman
email: helloHolaHuman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "holahuman.com" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username: jessanettica
github_username:  jessanettica

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
